#!/bin/bash
clear
echo "  ____   __     __   ____    ____       _____                                     ";
echo " |  _ \  \ \   / /  / __ \  |  _ \     / ____|                                    ";
echo " | |_) |  \ \_/ /  | |  | | | |_) |   | (___     ___   _ __  __   __   ___   _ __ ";
echo " |  _ <    \   /   | |  | | |  _ <     \___ \   / _ \ | '__| \ \ / /  / _ \ | '__|";
echo " | |_) |    | |    | |__| | | |_) |    ____) | |  __/ | |     \ V /  |  __/ | |   ";
echo " |____/     |_|     \____/  |____/    |_____/   \___| |_|      \_/    \___| |_|   ";
echo "                                                                                  ";
echo "                                                                                  ";
case $1 in
    run|start)
    sudo systemctl start byob-server
    ;;
    halt|stop)
    sudo systemctl stop byob-server
    ;;
    status)
    sudo systemctl status byob-server
    ;;
    inspect)
    tail ~/bootspool.log -f
    ;;
    help)
        echo "Commands around byob:"
        echo "byob help"
        echo "byob start - Start your byob"
        echo "byob stop - Stop your byob"
        echo "byob status - Get byob status"
        echo "byob tail - Tail the boot of your byob"
        ;;
    *) echo "> Use 'byob help' to get help";;
esac

    
esac
